spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/e-commerce
          jwk-set-uri: ${KEYCLOAK_URL}/realms/e-commerce/protocol/openid-connect/certs

mongo:
  url: ${DB_URL}
  database: ${DB_NAME}

cors:
  allowed-origins: http://localhost:3000

paypal:
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}
  mode: sandbox
  cancel-url: http://localhost:3000/ui/orders/%s/cancel/
  return-url: http://localhost:3000/ui/orders/%s/pay/

springdoc:
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: alpha
  override-with-generic-response: false
